#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_GREYBUS_GREYBUS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_GREYBUS_GREYBUS_H_

#define GREYBUS_VERSION_MAJOR	0x00
#define GREYBUS_VERSION_MINOR	0x01

#define CONTROL_BUNDLE_ID 0x00
#define CONTROL_CPORT_ID 0x00

#define BUNDLE_CLASS_CONTROL 0x00
#define BUNDLE_CLASS_AP 0x01
#define BUNDLE_CLASS_HID 0x05
#define BUNDLE_CLASS_POWER_SUPPLY 0x08
#define BUNDLE_CLASS_BRIDGED_PHY 0x0a
#define BUNDLE_CLASS_DISPLAY 0x0c
#define BUNDLE_CLASS_CAMERA 0x0d
#define BUNDLE_CLASS_SENSOR 0x0e
#define BUNDLE_CLASS_LIGHTS 0x0f
#define BUNDLE_CLASS_VIBRATOR 0x10
#define BUNDLE_CLASS_LOOPBACK 0x11
#define BUNDLE_CLASS_AUDIO 0x12
#define BUNDLE_CLASS_SVC 0x14
#define BUNDLE_CLASS_FIRMWARE 0x15
#define BUNDLE_CLASS_RAW 0xfe
#define BUNDLE_CLASS_VENDOR_SPECIFIC 0xff

#define CPORT_PROTOCOL_CONTROL 0x00
#define CPORT_PROTOCOL_AP 0x01
#define CPORT_PROTOCOL_GPIO 0x02
#define CPORT_PROTOCOL_I2C 0x03
#define CPORT_PROTOCOL_UART 0x04
#define CPORT_PROTOCOL_HID 0x05
#define CPORT_PROTOCOL_USB 0x06
#define CPORT_PROTOCOL_SDIO 0x07
#define CPORT_PROTOCOL_POWER_SUPPLY 0x08
#define CPORT_PROTOCOL_PWM 0x09
#define CPORT_PROTOCOL_SPI 0x0b
#define CPORT_PROTOCOL_DISPLAY 0x0c
#define CPORT_PROTOCOL_CAMERA_MANAGEMENT 0x0d
#define CPORT_PROTOCOL_SENSOR 0x0e
#define CPORT_PROTOCOL_LIGHTS 0x0f
#define CPORT_PROTOCOL_VIBRATOR 0x10
#define CPORT_PROTOCOL_LOOPBACK 0x11
#define CPORT_PROTOCOL_AUDIO_MANAGEMENT 0x12
#define CPORT_PROTOCOL_AUDIO_DATA 0x13
#define CPORT_PROTOCOL_SVC 0x14
#define CPORT_PROTOCOL_FIRMWARE 0x15
#define CPORT_PROTOCOL_CAMERA_DATA 0x16
#define CPORT_PROTOCOL_RAW 0xfe
#define CPORT_PROTOCOL_VENDOR_SPECIFIC 0xff

#define DESC_TYPE_INTERFACE 0x01
#define DESC_TYPE_STRING 0x02
#define DESC_TYPE_BUNDLE 0x03
#define DESC_TYPE_CPORT 0x04

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_GREYBUS_GREYBUS_H_ */
